# Generated by Django 4.1.7 on 2023-04-09 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chat_id', models.IntegerField(unique=True)),
                ('tl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_login', models.CharField(max_length=30, unique=True)),
                ('work_status', models.CharField(choices=[('Работает', 'Работает'), ('Отошел', 'Отошел'), ('Выходной', 'Выходной')], default='Работает', max_length=10)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.chat')),
            ],
        ),
        migrations.CreateModel(
            name='AwayLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.chat')),
            ],
        ),
    ]
