# Generated by Django 4.1.7 on 2023-03-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_awaylimit_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awaylimit',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.chat'),
        ),
    ]
