# Generated by Django 4.1.7 on 2023-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='tg_login',
            field=models.CharField(default='volchkovski', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
